export const FETCH_HETHONGRAP_REQUEST = "CumRap/CumRapReducer/FETCH_HETHONGRAP_REQUEST"

export const FETCH_HETHONGRAP_SUCESS = "CumRap/CumRapReducer/FETCH_HETHONGRAP_SUCESS"

export const FETCH_HETHONGRAP_FAILED = "CumRap/CumRapReducer/FETCH_HETHONGRAP_FAILED"